import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'

// Effective date of the current policy.
const EFFECTIVE = 'September 16, 2026'

// Public contact for privacy questions. NOTE: make sure this inbox exists (or
// change it to one you monitor) — Google Play requires a working contact.
const CONTACT_EMAIL = 'privacy@quiet-waters-meditation.com'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-medium text-deep-900">{title}</h2>
      <div className="mt-2 space-y-3 text-[0.95rem] leading-relaxed text-deep-600">{children}</div>
    </section>
  )
}

export function Privacy() {
  useEffect(() => {
    const prev = document.title
    document.title = 'Privacy Policy · Quiet Waters'
    return () => {
      document.title = prev
    }
  }, [])

  return (
    <div className="min-h-screen bg-mist-100 px-5 py-10">
      <div className="mx-auto max-w-2xl">
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-sm text-deep-500 underline-offset-2 hover:text-deep-700 hover:underline"
        >
          <ArrowLeft size={15} /> Quiet Waters
        </Link>

        <h1 className="mt-6 font-serif text-3xl text-deep-900">Privacy Policy</h1>
        <p className="mt-1.5 text-sm text-deep-500">Effective {EFFECTIVE}</p>

        <p className="mt-6 text-[0.95rem] leading-relaxed text-deep-700">
          Quiet Waters is built to keep your spiritual life private. Almost everything you do — your
          sittings, streak, notes, prayers, saved verses, and settings — stays on your device. There
          are no accounts, no ads, and we never sell your data.
        </p>

        <Section title="What stays on your device">
          <p>
            Quiet Waters is a “local-first” app. The following is stored only in the app on your
            device, and is never sent to us:
          </p>
          <ul className="ml-5 list-disc space-y-1">
            <li>Your sittings, streak, and history</li>
            <li>Prayers, notes, saved verses, and memory verses</li>
            <li>Your name (if you add one) and all of your settings</li>
          </ul>
          <p>
            You can export a backup file — which you control — or clear everything at any time in
            Settings.
          </p>
        </Section>

        <Section title="What leaves your device">
          <p>We keep the amount of data that leaves your device as small as possible:</p>
          <ul className="ml-5 list-disc space-y-2">
            <li>
              <span className="font-medium text-deep-800">Notifications (only if you turn them on):</span>{' '}
              to send the daily verse and occasional app updates, your device’s push subscription — a
              random address and keys generated by your browser, not your name or identity — is stored
              so we can deliver those messages. Turn notifications off anytime and it stops.
            </li>
            <li>
              <span className="font-medium text-deep-800">Anonymous usage analytics:</span> we use
              privacy-friendly, cookieless analytics (Vercel) that count visits in aggregate. They do
              not build a profile of you or track you across other sites.
            </li>
            <li>
              <span className="font-medium text-deep-800">Sharing (only when you choose):</span> when
              you share a verse or an encouragement, your device’s own share sheet sends it wherever
              you pick. We are not involved.
            </li>
          </ul>
        </Section>

        <Section title="What we don’t do">
          <ul className="ml-5 list-disc space-y-1">
            <li>No accounts or sign-in.</li>
            <li>No ads, and no advertising trackers.</li>
            <li>We never sell or rent your data.</li>
            <li>We don’t access your contacts, location, photos, or microphone.</li>
          </ul>
        </Section>

        <Section title="Children">
          <p>
            Quiet Waters is intended for a general audience and does not knowingly collect personal
            information from children.
          </p>
        </Section>

        <Section title="Your control">
          <p>At any time you can:</p>
          <ul className="ml-5 list-disc space-y-1">
            <li>Turn notifications on or off in Settings.</li>
            <li>Export a backup of your data, or clear your history, in Settings.</li>
            <li>Uninstall the app or clear your browser data to remove everything on your device.</li>
          </ul>
        </Section>

        <Section title="Changes to this policy">
          <p>
            If this policy changes, we’ll update the date at the top. Continued use means you accept
            the updated policy.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions about privacy? Email{' '}
            <a
              href={`mailto:${CONTACT_EMAIL}`}
              className="text-water-600 underline-offset-2 hover:underline"
            >
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </Section>

        <div className="mt-10 border-t border-line pt-6">
          <Link
            to="/meditate"
            className="text-sm text-water-600 underline-offset-2 hover:underline"
          >
            ← Back to Quiet Waters
          </Link>
        </div>
      </div>
    </div>
  )
}
